version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: riwi_postgres_chat
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: bd_riwi_chat_clan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_password_2026
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  pgdata:
